version: "3"
services:
  db:
    image: postgres
    ports:
      - "6432:5432"
    volumes:
      - axum_postgres:/var/lib/postgresql/data
    environment:
      - DATABASE=axum
      - POSTGRES_USER=axum
      - POSTGRES_PASSWORD=axum
volumes:
  axum_postgres:
